### ISSUE TITLE
social share link preview improvements

### ISSUE THREAD

**Issue by gerbrent** [ironicbadger/pms-wiki#103]
When sharing PMS links via social means, the preview is rather mundane but mostly problematic: It's pixelated. Or doesn't exist at all..

I'd like to argue this type of preview can be much improved.

#### Signal messenger link preview:
Here I think it's just a stretched favicon?
![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/7c646c45-9444-474c-87b9-c820f273ed2e)

#### Telegram: 
no preview at all..
![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/8d8ab51e-62cf-4d04-a7c4-acc750cfaae4)

#### Element:
![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/93aa74d5-a2cd-43a3-84ac-7743c2ce8cbd)

---

Preview could look as fancy as:

![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/421b8211-e332-4e7c-81af-a23ca3e5f3e1)
![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/de7348f0-4db3-4ee3-af8b-7030ff300372)

link to click/share for testing: https://perfectmediaserver.com/06-hardware/new-drive-burnin/

**Comment by ironicbadger** [comment]
<img width="356" alt="Screenshot 2023-12-27 at 12 43 27" src="https://github.com/ironicbadger/pms-wiki/assets/2773080/f85d1a5b-2bbd-44d7-b7b4-074e134ab90f">

Added https://squidfunk.github.io/mkdocs-material/plugins/social/#layouts-default
