### ISSUE TITLE
Real-time parity solutions as opposed to SnapRAID?

### ISSUE THREAD

**Issue by jamesWalker55** [ironicbadger/pms-wiki#105]
The SnapRAID section of the Wiki states that SnapRAID isn't suitable for real-time use cases, and users should consider an alternative. However the page makes no mention of any alternatives. I've did some initial Googling and found no good solutions as well. For a use-case like running daily backups to a NAS or running a database, what real-time alternatives to SnapRAID are there?

**Comment by ironicbadger** [comment]
unraid if you want the JBOD style is your only option
