### ISSUE TITLE
Where is snapraid parity data stored on a zfs with mergerfs configuration?

### ISSUE THREAD

**Issue by tristan-k** [IronicBadger/pms-wiki#30]
I just finished reading the section [ZFS with MergerFS](https://perfectmediaserver.com/advanced/combine-zfs-and-others/) and from my understanding it is not clear where the snapraid parity data for the mergerfs disks is actually stored. In the diagram for the snapraid configuration is a extra parity disk. This disk is missing in the diagram for the zfs mergerfs combined configuration. This is confusing.

Is it stored on the mirrored zfs pool or is stored on 1 of the 5 disks or is stored on a unmentioned disk 6?

> MergerFS also does not provide mitigation for drive failure, this is where SnapRAID comes in. It is used to calculate a snapshot of parity across all data drives that are not using ZFS. The ZFS drives are configured in a mirror and take care of their own parity and data integrity checks.

Something like this:

![zfs_snapraid_diagram](https://user-images.githubusercontent.com/732025/112683184-73ca0480-8e71-11eb-8639-79e940686de7.jpg)

**Comment by IronicBadger** [comment]
Not sure I quite see the confusion tbh. Perhaps I'm too close to the forest to see the trees.
