### ISSUE TITLE
Ubuntu Server restored /dev/disk/by-id/ata-

### ISSUE THREAD

**Issue by NLZ** [IronicBadger/pms-wiki#34]
I just checked Ubuntu Server 20.04.2 and it contains the previously missing devices of `/dev/disk/by-id/ata-*`, but also kept the `scsi-*` ones.
```
nlz@chaos:/mnt$ ls -l /dev/disk/by-id/ | grep sdc$
lrwxrwxrwx 1 root root  9 Jun 30 13:36 ata-ST4000VN008-2DR166_ZDH4RTVD -> ../../sdc
lrwxrwxrwx 1 root root  9 Jun 30 13:36 scsi-0ATA_ST4000VN008-2DR1_ZDH4RTVD -> ../../sdc
lrwxrwxrwx 1 root root  9 Jun 30 13:36 scsi-1ATA_ST4000VN008-2DR166_ZDH4RTVD -> ../../sdc
lrwxrwxrwx 1 root root  9 Jun 30 13:36 scsi-35000c500b27d88be -> ../../sdc
lrwxrwxrwx 1 root root  9 Jun 30 13:36 scsi-SATA_ST4000VN008-2DR1_ZDH4RTVD -> ../../sdc
lrwxrwxrwx 1 root root  9 Jun 30 13:36 wwn-0x5000c500b27d88be -> ../../sdc
```
So maybe the advice against Ubuntu Server could be downgraded into a warning that Canonical likes to mess stuff up.

**Comment by IronicBadger** [comment]
Oh really....? Very nice. I will take a look at this at some point. I've actually switched to Proxmox recently and am not using Ubuntu at all!
