### ISSUE TITLE
Hardware caveats and considerations

### ISSUE THREAD

**Issue by korden32** [ironicbadger/pms-wiki#42]
Maybe I'll write a PR at some point, but for now just generic thoughts:
- HDD mounts in cases. Modern helium HDDs don't have bottom middle holes and biggest ones (>12Tb) also don't have side middle holes.
- Powering multiple HDDs. With modular PSUs you can usually ask manufacturer about proper additional cables with 3x or 4xSATA with T- or Y-type SATA connectors with various lengths. Avoid using "one Molex/SATA to 5 SATA" adapters as this may cause failures due to high current on startup and bad adapter quality.
- Hot-swap server cages and other "server" things are usually very noisy and designed to be used with high-RPM small fans. You probably want to avoid them at home because of that. Example: 3x5.25">5x3.5" server cage with 92/80mm fan (like SuperMicro CSE-M35T) would be louder than non-hotswappable bracket from China with 120mm fan.

**Comment by ironicbadger** [comment]
Please reopen if you do write that PR - it looks like a good topic!
