### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by GoofyAF** [ironicbadger/pms-wiki#43]
Hi Alex,

Great guide, thanks for your work.

The link on  [docker-compose](https://perfectmediaserver.com/tech-stack/docker-compose.html) page to the bash alias section on the [quality of life tweaks](https://perfectmediaserver.com/day-two/quality-of-life-tweaks.html) page is [broken](https://perfectmediaserver.com/day-two/quality-of-life-tweaks/#bash-aliases).

It appears that the list of bash aliases on the first page is not duplicated on the second, and there is not a corresponding `#bash-alias` heading or tag in the second page.

**Comment by ironicbadger** [comment]
Fixed, thanks. Via [77dab02e5bc10925cf1698220f60a5f3c2b32ce7](https://github.com/ironicbadger/pms-wiki/commit/77dab02e5bc10925cf1698220f60a5f3c2b32ce7).
