### ISSUE TITLE
Broken link in the "SnapRAID" section

### ISSUE THREAD

**Issue by SituesmonpainJetejetterai** [ironicbadger/pms-wiki#45]
Hi, it seems that the picture describing the setup of `SnapRAID` with `mergerfs` is missing. Can you add it back? The pictures really help to visualise a lot better. Thanks :)

Link to file: https://github.com/ironicbadger/pms-wiki/blob/main/docs/tech-stack/snapraid.md

**Comment by ironicbadger** [comment]
Fixed with [this commit](6d7f3fe0c3137dd07c0943401aa14c37182e20e2). Thanks!
