### ISSUE TITLE
Proxmox / storage?

### ISSUE THREAD

**Issue by imagesafari** [ironicbadger/pms-wiki#48]
How are you setting up your storage / disks when you moved to proxmox?

Great stuff, thanks!

**Comment by ironicbadger** [comment]
The same as before really.

Media under `/mnt/storage`, precious data under `/mnt/tank/fuse` which is a ZFS mirror.

**Comment by jonasjeeliasson** [comment]
Follow up. I'm about to setup my own PMS following the great stuff you have written here. I went and installed Proxmox and spun up a LXC container with Ubuntu and now trying to figure out how I pass in the drives and setup mergerfs in the best way but noticed that I can't pass in full disk as is into a LXC or maybe I'm missing something, but seems I can only bind directories? How have you set it up?

1. Ubuntu VM pass through drives as is and do everything in the VM with mergerfs etc?
2. Ubuntu LXC with directory mounts and then mergerfs in Ubuntu container?
3. Setting up drives in Proxmox host with mergerfs and mounting the resulting pool in Ubuntu VM/LXC? 
4. Or something else? :)

Thanks for a great site and resources for setting up a perfect media server!
