### ISSUE TITLE
image for MergerFS SnapRAID diagram is broken

### ISSUE THREAD

**Issue by xijio** [ironicbadger/pms-wiki#52]
On https://perfectmediaserver.com/tech-stack/snapraid/ the image for MergerFS SnapRAID diagram is broken.

It points to https://perfectmediaserver.com/tech-stack/images/diagram-mergerfs-snapraid.png where it should point to https://perfectmediaserver.com/images/diagram-mergerfs-snapraid.png.

It appears this change broke it: https://github.com/ironicbadger/pms-wiki/commit/6d7f3fe0c3137dd07c0943401aa14c37182e20e2

On git hub (https://github.com/ironicbadger/pms-wiki/blob/main/docs/tech-stack/snapraid.md) ../images works
but on the pms site (https://perfectmediaserver.com/tech-stack/snapraid/) it needs to be ../../images

**Comment by ironicbadger** [comment]
Fixed with commit [1b587fdb8416dd59e470fd3dab8aa20932ab8426](https://github.com/ironicbadger/pms-wiki/commit/1b587fdb8416dd59e470fd3dab8aa20932ab8426)
