### ISSUE TITLE
Documentation / recommendation on "tiered storage" with mergerfs

### ISSUE THREAD

**Issue by TheLinuxGuy** [ironicbadger/pms-wiki#60]
I've been looking at replacing unraid and came across your wiki (very helpful btw). It has given me several ideas to roll-my-own ubuntu box to replace unraid with snapraid. There is one piece missing in this puzzle though: unraid's "mover" and the ability to use a NVME disk as "cache" for all my data. 

Could you make some recommendations/documentation discussing "tiered storage" model for PMS? I think many people would want it.

Unraid's ability to have FIFO writes to a NVME then later offloaded onto spinning hard drives (with spun-down settings to lower power consumption) is a major feature for home media server users. Snapraid (as you suggested) fixes many flaws and gaps that unraid model has in term of data assurance/checksumming. 

I think a blog post and configuration examples with a "mover like script" to take care of transitioning data off NVME back onto the archive/spinning-rust disks would be great. While the author of mergerfs @trapexit has some information on this (https://github.com/trapexit/mergerfs#tiered-caching); a working example on  your blog I think would greatly help others trying to learn many new things at once to replace unraid.

**Comment by ironicbadger** [comment]
Tbh, I don't have much to add over the official documentation. It's something I'll add to the list for sure though. Thanks for bringing it up.
