### ISSUE TITLE
Proxmox and getting storage to Ubuntu VM/LXC

### ISSUE THREAD

**Issue by jonasjeeliasson** [ironicbadger/pms-wiki#67]
Hello! 

First off, thanks for a great site and resources for setting up a perfect media server!

I'm about to setup my own PMS following your guides here. I went and installed Proxmox and spun up a LXC container with Ubuntu and now trying to figure out how I pass in the drives and setup mergerfs in the best way but noticed that I can't pass in full disk as is into a LXC or maybe I'm missing something, but seems I can only bind directories? How have you set it up?

1. Ubuntu VM pass through drives as is and do everything in the VM with mergerfs etc?
2. Ubuntu LXC with directory mounts and then mergerfs in Ubuntu container?
3. Setting up drives in Proxmox host with mergerfs and mounting the resulting pool in Ubuntu VM/LXC?
4. Or something else? :)

Are there something to be extra careful with here to not bit yourself in the foot later, something that doesn't play nice with mergerfs or so?

Thanks again!

**Comment by RealOrangeOne** [comment]
Storage on the host is probably easiest. It avoids a bunch of issues around startup order, and keeps storage a task handled solely by the host, which makes management easier.
