### ISSUE TITLE
`go to repo` header item - should open in new window/tab 

### ISSUE THREAD

**Issue by gerbrent** [ironicbadger/pms-wiki#69]
The `go to repo` header item when clicked -> presently opens in the current window/tab.

Recommend making this link open in a NEW window/tab, if possible `\/`

![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/2c571730-484b-4978-9fa1-93ac72582143)
  

https://github.com/ironicbadger/pms-wiki/blob/356953e0efae513d79d41adda97cb024eeb3fcd2/mkdocs.yml#L2-L4

**Comment by ironicbadger** [comment]
https://github.com/squidfunk/mkdocs-material/discussions/3660

**Comment by ironicbadger** [comment]
Fixed with https://github.com/ironicbadger/pms-wiki/blob/a5281f1fdc44aa97142353fcb5d1ad8042930d00/mkdocs.yml#L48
