### ISSUE TITLE
Main logo - use SVG instead of PNG to reduce load time

### ISSUE THREAD

**Issue by gerbrent** [ironicbadger/pms-wiki#72]
The current main home page logo is a png (i.e. raster) image, and thus ~500 kB.

This could be vectorized to a svg to reduce load times and size. 

![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/c2a1849c-c369-46b0-be68-588f9128471a)

(appeared to load last for me on Starlink tonight, hence prompted the change suggestion..

**Comment by ironicbadger** [comment]
Not an SVG but 500kb down to 42kb as a transparent PNG. #75
