### ISSUE TITLE
main logo - dark mode no worky!

### ISSUE THREAD

**Issue by gerbrent** [ironicbadger/pms-wiki#73]
![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/0c7aff30-a1cc-4bbf-843d-74361939640a)

**Comment by ironicbadger** [comment]
#75 

<img width="990" alt="image" src="https://github.com/ironicbadger/pms-wiki/assets/2773080/cdc86ea5-997c-4848-881f-d9452eec904c">
