### ISSUE TITLE
`Licensed under GPLv3` - for content? May be inappropriate.

### ISSUE THREAD

**Issue by gerbrent** [ironicbadger/pms-wiki#77]
The site footer reads:

> Licensed under GPLv3 

As seen here:
![image](https://github.com/ironicbadger/pms-wiki/assets/7018928/6a1db9b9-5631-4f1d-9a8e-56332acf1dea)

The question becomes: 
Is this referring to the content? The software?

If the license is intended for the content, then... isn't GPL a software-specific license, and wouldn't something like [Creative Commons](https://creativecommons.org/choose/) be more appropriate?

**Comment by rzzzzss** [comment]
> The site footer reads:
> 
> > Licensed under GPLv3
> 
> As seen here: ![image](https://user-images.githubusercontent.com/7018928/262453502-6a1db9b9-5631-4f1d-9a8e-56332acf1dea.png)
> 
> The question becomes: Is this referring to the content? The software?
> 
> If the license is intended for the content, then... isn't GPL a software-specific license, and wouldn't something like [Creative Commons](https://creativecommons.org/choose/) be more appropriate?

**Comment by rzzzzss** [comment]
> The site footer reads:
> 
> > Licensed under GPLv3
> 
> As seen here: ![image](https://user-images.githubusercontent.com/7018928/262453502-6a1db9b9-5631-4f1d-9a8e-56332acf1dea.png)
> 
> The question becomes: Is this referring to the content? The software?
> 
> If the license is intended for the content, then... isn't GPL a software-specific license, and wouldn't something like [Creative Commons](https://creativecommons.org/choose/) be more appropriate?

**Comment by ironicbadger** [comment]
https://github.com/ironicbadger/pms-wiki/commit/b181aa471770875969c7be57071f08bc13d82c21
