### ISSUE TITLE
Preferred method to add further context to an existing case review?

### ISSUE THREAD

**Issue by teambvd** [ironicbadger/pms-wiki#97]
I've forked the PMS wiki to add my own review of a couple chassis I've worked with over the years, and saw the [CS380](https://perfectmediaserver.com/06-hardware/cases/#silverstone-cs380) already posted there - I've had some extensive experience with this case, [modding it](https://forums.unraid.net/topic/113007-ye-olde-cs380b-the-backup-server/) due to some design issues with air flow, along with some backplane/sled concerns, but wasn't sure how one might go about adding such details to an existing review.

How (if at all that is) would you prefer such things be handled?

**Comment by ironicbadger** [comment]
I don't know :)

Feel free to submit a PR with a suggestion!
